### PR TITLE
Feature for comment popup

### PR DESCRIPTION
**Pull request by kinginthenorthcodez**
###[Display Comments pop up with selected item's details - Student B #14](https://github.com/luis-pomare/the-boys-seasons/issues/14)

- Create a comments popup only with the top section (displaying details of the selected item)
- When the popup loads, the web app retrieves data from the selected API and shows details about the selected item.
- Add an event to the button prepared by your teammate that will open your popup.

### CODE REVIEW

**Comment by kinginthenorthcodez** [comment]
@luis-pomare  Resolved conflict 👍🏽

**Review by luis-pomare — APPROVED** [review]
Nice!!!
Good job implementing the modules' distribution.
good and clean code
Let's merge it and continue working 👍 
✔️

**Comment by kinginthenorthcodez** [comment]
@luis-pomare  Thanks for that review 👍🏽

**Comment by kinginthenorthcodez** [comment]
Merge #25 into development

**Pull request merged**
